FROM python:3.11-slim

# System dependencies for OpenCV
RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python deps
COPY requirements_id.txt .
RUN pip install --no-cache-dir -r requirements_id.txt

# Copy logic and create storage folder
COPY . .
RUN mkdir -p data/students_faces

EXPOSE 8002
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]