FROM python:3.11-slim
WORKDIR /app
COPY requirements_gateway.txt .
RUN pip install --no-cache-dir -r requirements_gateway.txt
COPY . .
# We expose 8000 as the main entry point for the user
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]